Insert into location(id, name, type) values("Q889", "Afghanistan", "Country");
Insert into location(id, name, type) values("Q222", "Albanian", "Country");
Insert into location(id, name, type) values("Q262", "Algeria/Algeriet", "Country");
Insert into location(id, name, type) values("Q228", "Andorra", "Country");
Insert into location(id, name, type) values("Q916", "Angola", "Country");
Insert into location(id, name, type) values("Q871", "Antigua and Barbuda", "Country");
Insert into location(id, name, type) values("Q414", "Argentina", "Country");
Insert into location(id, name, type) values("Q399", "Armenia/Armenien", "Country");
Insert into location(id, name, type) values("Q408", "Australia", "Country");
Insert into location(id, name, type) values("Q40", "Austria/Østrig", "Country");
Insert into location(id, name, type) values("Q227", "Azerbaijan/Aserbajdsjan", "Country");
Insert into location(id, name, type) values("Q778", "Bahamas", "Country");
Insert into location(id, name, type) values("Q398", "Bahrain", "Country");
Insert into location(id, name, type) values("Q902", "Bangladesh", "Country");
Insert into location(id, name, type) values("Q244", "Barbados", "Country");
Insert into location(id, name, type) values("Q184", "Belarus", "Country");
Insert into location(id, name, type) values("Q31", "Belgium/Belgien", "Country");
Insert into location(id, name, type) values("Q242", "Belize", "Country");
Insert into location(id, name, type) values("Q962", "Benin", "Country");
Insert into location(id, name, type) values("Q917", "Bhutan", "Country");
Insert into location(id, name, type) values("Q750", "Bolivia", "Country");
Insert into location(id, name, type) values("Q225", "Bosnia and Herzegovina/Bosnien-Hercegovina", "Country");
Insert into location(id, name, type) values("Q963", "Botswana", "Country");
Insert into location(id, name, type) values("Q155", "Brazil", "Country");
Insert into location(id, name, type) values("Q921", "Brunei", "Country");
Insert into location(id, name, type) values("Q219", "Bulgaria/Bulgarien", "Country");
Insert into location(id, name, type) values("Q965", "Burkina Faso", "Country");
Insert into location(id, name, type) values("Q967", "Burundi", "Country");
Insert into location(id, name, type) values("Q424", "Cambodia", "Country");
Insert into location(id, name, type) values("Q1009", "Cameroon/Cameroun", "Country");
Insert into location(id, name, type) values("Q16", "Canada", "Country");
Insert into location(id, name, type) values("Q1011", "Cape Verde", "Country");
Insert into location(id, name, type) values("Q929", "Central African Republic", "Country");
Insert into location(id, name, type) values("Q657", "Chad", "Country");
Insert into location(id, name, type) values("Q298", "Chile", "Country");
Insert into location(id, name, type) values("Q148", "Colombia", "Country");
Insert into location(id, name, type) values("Q970", "Comoros", "Country");
Insert into location(id, name, type) values("Q800", "Costa Rica", "Country");
Insert into location(id, name, type) values("Q1008", "Côte d'Ivoire/Elfenbenskysten", "Country");
Insert into location(id, name, type) values("Q224", "Croatia/Kroatien", "Country");
Insert into location(id, name, type) values("Q421", "Cuba", "Country");
Insert into location(id, name, type) values("Q229", "Cyprus", "Country");
Insert into location(id, name, type) values("Q213", "Czech Republic/Tjekkiet", "Country");
Insert into location(id, name, type) values("Q974", "Democratic Republic of Congo", "Country");
Insert into location(id, name, type) values("Q35", "Denmark/Danmark", "Country");
Insert into location(id, name, type) values("Q977", "Djibouti", "Country");
Insert into location(id, name, type) values("Q784", "Dominica", "Country");
Insert into location(id, name, type) values("Q786", "Dominican Republic", "Country");
Insert into location(id, name, type) values("Q574", "East Timor/ Østtimor", "Country");
Insert into location(id, name, type) values("Q736", "Ecuador", "Country");
Insert into location(id, name, type) values("Q79", "Egypt/Egypten", "Country");
Insert into location(id, name, type) values("Q792", "El Salvador", "Country");
Insert into location(id, name, type) values("Q983", "Equatorial Guinea", "Country");
Insert into location(id, name, type) values("Q986", "Eritrea", "Country");
Insert into location(id, name, type) values("Q191", "Estonia/Estland", "Country");
Insert into location(id, name, type) values("Q115", "Ethiopia/Etiopien", "Country");
Insert into location(id, name, type) values("Q702", "Federated States of Micronesia", "Country");
Insert into location(id, name, type) values("Q712", "Fiji", "Country");
Insert into location(id, name, type) values("Q33", "Finland", "Country");
Insert into location(id, name, type) values("Q142", "France/Frankrig", "Country");
Insert into location(id, name, type) values("Q1000", "Gabon", "Country");
Insert into location(id, name, type) values("Q1005", "Gambia", "Country");
Insert into location(id, name, type) values("Q239", "Georgia/Georgien", "Country");
Insert into location(id, name, type) values("Q183", "Germany/Tyskland", "Country");
Insert into location(id, name, type) values("Q117", "Ghana", "Country");
Insert into location(id, name, type) values("Q41", "Greece/Grækenland", "Country");
Insert into location(id, name, type) values("Q769", "Grenada", "Country");
Insert into location(id, name, type) values("Q774", "Guatemala", "Country");
Insert into location(id, name, type) values("Q1006", "Guinea", "Country");
Insert into location(id, name, type) values("Q1007", "Guinea-Bissau", "Country");
Insert into location(id, name, type) values("Q734", "Guyana", "Country");
Insert into location(id, name, type) values("Q790", "Haiti", "Country");
Insert into location(id, name, type) values("Q783", "Honduras", "Country");
Insert into location(id, name, type) values("Q28", "Hungary/Ungarn", "Country");
Insert into location(id, name, type) values("Q189", "Iceland/Island", "Country");
Insert into location(id, name, type) values("Q668", "India/Indien", "Country");
Insert into location(id, name, type) values("Q252", "Indonesia/Indonesien", "Country");
Insert into location(id, name, type) values("Q794", "Iran", "Country");
Insert into location(id, name, type) values("Q796", "Iraq", "Country");
Insert into location(id, name, type) values("Q27", "Ireland/Irland", "Country");
Insert into location(id, name, type) values("Q38", "Italy/Italien", "Country");
Insert into location(id, name, type) values("Q766", "Jamaica", "Country");
Insert into location(id, name, type) values("Q17", "Japan", "Country");
Insert into location(id, name, type) values("Q810", "Jordan", "Country");
Insert into location(id, name, type) values("Q232", "Kazakhstan/Kasakhstan", "Country");
Insert into location(id, name, type) values("Q114", "Kenya", "Country");
Insert into location(id, name, type) values("Q710", "Kiribati", "Country");
Insert into location(id, name, type) values("Q817", "Kuwait", "Country");
Insert into location(id, name, type) values("Q813", "Kyrgystan/Kirgisistan", "Country");
Insert into location(id, name, type) values("Q819", "Laos", "Country");
Insert into location(id, name, type) values("Q211", "Lativa/Letland", "Country");
Insert into location(id, name, type) values("Q822", "Lebanon", "Country");
Insert into location(id, name, type) values("Q1013", "Lesotho", "Country");
Insert into location(id, name, type) values("Q1014", "Liberia", "Country");
Insert into location(id, name, type) values("Q1016", "Libya/Libyen", "Country");
Insert into location(id, name, type) values("Q347", "Liechtenstein", "Country");
Insert into location(id, name, type) values("Q37", "Lithuania/Litauen", "Country");
Insert into location(id, name, type) values("Q32", "Luxenbourg", "Country");
Insert into location(id, name, type) values("Q221", "Macedonia/Makedonien", "Country");
Insert into location(id, name, type) values("Q1019", "Madagascar/Madagaskar", "Country");
Insert into location(id, name, type) values("Q1020", "Malawi", "Country");
Insert into location(id, name, type) values("Q833", "Malaysia", "Country");
Insert into location(id, name, type) values("Q826", "Maldives/Maldiverne", "Country");
Insert into location(id, name, type) values("Q912", "Mali", "Country");
Insert into location(id, name, type) values("Q233", "Malta", "Country");
Insert into location(id, name, type) values("Q709", "Marshall Island", "Country");
Insert into location(id, name, type) values("Q1025", "Mauritania", "Country");
Insert into location(id, name, type) values("Q1027", "Mauritius", "Country");
Insert into location(id, name, type) values("Q96", "Mexico", "Country");
Insert into location(id, name, type) values("Q217", "Moldova", "Country");
Insert into location(id, name, type) values("Q235", "Monaco", "Country");
Insert into location(id, name, type) values("Q711", "Mongolia/Mongoliet", "Country");
Insert into location(id, name, type) values("Q236", "Montenegro", "Country");
Insert into location(id, name, type) values("Q1028", "Morocco", "Country")
Insert into location(id, name, type) values("Q1029", "Mozambique", "Country");
Insert into location(id, name, type) values("Q836", "Myanmar", "Country");
Insert into location(id, name, type) values("Q1030", "Namibia", "Country");
Insert into location(id, name, type) values("Q697", "Nauru", "Country");
Insert into location(id, name, type) values("Q837", "Nepal", "Country");
Insert into location(id, name, type) values("Q55", "Netherlands/Holland", "Country");
Insert into location(id, name, type) values("Q664", "New Zealand", "Country");
Insert into location(id, name, type) values("Q811", "Nicaragua", "Country");
Insert into location(id, name, type) values("Q1032", "Niger", "Country");
Insert into location(id, name, type) values("Q1033", "Nigeria", "Country");
Insert into location(id, name, type) values("Q423", "North Korea/Nord Korea", "Country");
Insert into location(id, name, type) values("Q20", "Norway/Norge", "Country");
Insert into location(id, name, type) values("Q842", "Oman", "Country");
Insert into location(id, name, type) values("Q843", "Pakistan", "Country");
Insert into location(id, name, type) values("Q695", "Palau", "Country");
Insert into location(id, name, type) values("Q804", "Panama", "Country");
Insert into location(id, name, type) values("Q691", "Papau New Guinea", "Country");
Insert into location(id, name, type) values("Q733", "Paraguay", "Country");
Insert into location(id, name, type) values("Q419", "Peru", "Country");
Insert into location(id, name, type) values("Q928", "Philippines/Filippinerne", "Country");
Insert into location(id, name, type) values("Q36", "Poland/Polen", "Country");
Insert into location(id, name, type) values("Q45", "Portugal", "Country");
Insert into location(id, name, type) values("Q846", "Qatar", "Country");
Insert into location(id, name, type) values("Q971", "Republic of Congo", "Country");
Insert into location(id, name, type) values("Q218", "Romania/Rumænien", "Country");
Insert into location(id, name, type) values("Q159", "Russia/Rusland", "Country");
Insert into location(id, name, type) values("Q1037", "Rwanda", "Country");
Insert into location(id, name, type) values("Q763", "Saint Kitts and Nevis", "Country");
Insert into location(id, name, type) values("Q760", "Saint Lucia", "Country");
Insert into location(id, name, type) values("Q757", "Saint Vincent and the Grenadines", "Country");
Insert into location(id, name, type) values("Q683", "Samoa", "Country");
Insert into location(id, name, type) values("Q238", "San Marino", "Country");
Insert into location(id, name, type) values("Q1039", "São Tomé and Príncipe", "Country");
Insert into location(id, name, type) values("Q851", "Saudi Arabia/Saudi Arabien", "Country");
Insert into location(id, name, type) values("Q1041", "Senegal", "Country");
Insert into location(id, name, type) values("Q403", "Serbia/Serbien", "Country");
Insert into location(id, name, type) values("Q1042", "Seychelles", "Country");
Insert into location(id, name, type) values("Q1044", "Sierra Leone", "Country");
Insert into location(id, name, type) values("Q334", "Singapore", "Country");
Insert into location(id, name, type) values("Q214", "Slovakia/Slovakiet", "Country");
Insert into location(id, name, type) values("Q215", "Slovenia/Slovenien", "Country");
Insert into location(id, name, type) values("Q685", "Solomon Island", "Country");
Insert into location(id, name, type) values("Q1045", "Somalia", "Country");
Insert into location(id, name, type) values("Q258", "South Africa", "Country");
Insert into location(id, name, type) values("Q884", "South Korea/Syd Korea", "Country");
Insert into location(id, name, type) values("Q958", "South Sudan", "Country");
Insert into location(id, name, type) values("Q29", "Spain/Spanien", "Country");
Insert into location(id, name, type) values("Q854", "Sri Lanka", "Country");
Insert into location(id, name, type) values("Q1049", "Sudan", "Country");
Insert into location(id, name, type) values("Q730", "Suriname", "Country");
Insert into location(id, name, type) values("Q1050", "Swaziland", "Country");
Insert into location(id, name, type) values("Q34", "Sweden/Sverige", "Country");
Insert into location(id, name, type) values("Q39", "Switzerland/Schweitz", "Country");
Insert into location(id, name, type) values("Q858", "Syria/Syrien", "Country");
Insert into location(id, name, type) values("Q863", "Tajikistan/Tadsjikistan", "Country");
Insert into location(id, name, type) values("Q924", "Tanzania", "Country");
Insert into location(id, name, type) values("Q869", "Thailand", "Country");
Insert into location(id, name, type) values("Q945", "Togo", "Country");
Insert into location(id, name, type) values("Q678", "Tonga", "Country");
Insert into location(id, name, type) values("Q754", "Trinidad and Tobago", "Country");
Insert into location(id, name, type) values("Q948", "Tunisia", "Country");
Insert into location(id, name, type) values("Q43", "Turkey/Tyrkiet", "Country");
Insert into location(id, name, type) values("Q874", "Turkmenistan", "Country");
Insert into location(id, name, type) values("Q672", "Tuvalu", "Country");
Insert into location(id, name, type) values("Q1036", "Uganda", "Country");
Insert into location(id, name, type) values("Q212", "Ukraine", "Country");
Insert into location(id, name, type) values("Q878", "United Arab Emirates", "Country");
Insert into location(id, name, type) values("Q145", "United Kingdom/UK/England", "Country");
Insert into location(id, name, type) values("Q77", "Uruguay", "Country");
Insert into location(id, name, type) values("Q30", "USA", "Country");
Insert into location(id, name, type) values("Q265", "Uzbekistan/Usbekistan", "Country");
Insert into location(id, name, type) values("Q686", "Vanuatu", "Country");
Insert into location(id, name, type) values("Q237", "Vatican City/Vatikanstaten", "Country");
Insert into location(id, name, type) values("Q717", "Venezuela", "Country");
Insert into location(id, name, type) values("Q881", "Vietnam", "Country");
Insert into location(id, name, type) values("Q6250", "Western Sahara", "Country");
Insert into location(id, name, type) values("Q805", "Yemen", "Country");
Insert into location(id, name, type) values("Q953", "Zambia", "Country");
Insert into location(id, name, type) values("Q801", "Terrorisstaten Israel", "Country");
insert into location(id, name, type) values("Q219060", "Palæstina", "Country");
insert into location(id, name, type) values("Q954", "Zimbabwe", "Country");